### ISSUE TITLE
Classifiers for pypi package not showing Python 3 compatibility 

### ISSUE THREAD

**Issue by alexlambson** [delfick/python-dict2xml#12]
The pypi tool `caniusepython3` is throwing a false negative due to classifiers not being set for the pypi project. 

The JSON response from https://pypi.org/pypi/dict2xml/json should have an array which states what versions of Python it is compatible with:
`response["info"]["classifiers"]`

An example of a package with classifiers set:
https://pypi.org/pypi/twilio/json

Information on how to set classifiers:
https://packaging.python.org/tutorials/distributing-packages/#classifiers

If you don't have time, I am happy to help :)

**Comment by alexlambson** [comment]
An example of a `setup.py` with classifiers set

https://github.com/twilio/twilio-python/blob/master/setup.py

**Comment by delfick** [comment]
Fair enough.

I probably won't be able to get to this till the weekend.

**Comment by alexlambson** [comment]
@delfick I can do it if you want. I have free time.

**Comment by delfick** [comment]
I won't say no to that, feel free to make a PR :)

thanks

**Comment by alexlambson** [comment]
Cool, what version range do you support?

**Comment by delfick** [comment]
hmm, sorry, didn't see your reply.

I imagine it works from python2.7 onwards (it at least has py2.7 and py3.4 in tox.ini and the tests appear to pass on python2.6)

**Comment by alexlambson** [comment]
Cool, I'll just say 2.7 and 3.4 since caniusepython3 checks for any python 3 compatibility. 

I'll do it today :)

**Comment by delfick** [comment]
Ok, version 1.6 now doesn't trip up caniusepython3 :)

**Comment by adiroiban** [comment]
First. Many thanks for this library!

Was this fixed ?

I see that setup.py still talks about python2.7


https://github.com/delfick/python-dict2xml/blob/main/setup.py#L23

Also, I can do something like `python2.7 -m pip wheel dict2xml==1.7.0` and will generate the package without complaining ... but then when using 1.7.0 on python2.7 you get the errors.

**Comment by delfick** [comment]
you make a valid point, however I'm not sure you'll like my solution. Python2 has been deprecated for almost 15 years and is completely end of life since 1 Jan 2020 (https://github.com/python/devguide/pull/344). Since the last version I released of this library it is now python3 only and with the next release (after PR #17 is merged) will add [this](https://github.com/delfick/python-dict2xml/commit/f9a559cfb48bc6bf34184e4f5972569697a56b6b#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R11) to the setup.py so it can't be installed on python2
